### PR TITLE
Fixes #144; swap position x z coordinate interpretation

### LINKED ISSUE #144: swap position x z coordinate interpretation
Undo what was done to close issue #78 .

What I didn't realize when that was implemented is that it switched us from a right-handed coordinate system to a left-handed coordinate system. We want to go back to right-handed to make it simpler to export to 3D tools such as oxDNA.

Let's ensure backward compatibility here by bumping the minor version number once this is fixed, checking the version on import from a .sc file, and swapping the x-z coordinates on prior versions.

Related to web interface issue [488](https://github.com/UC-Davis-molecular-computing/scadnano/issues/488).

### PR DESCRIPTION
**Pull request by UnHumbleBen**
Do not merge until https://github.com/UC-Davis-molecular-computing/scadnano/issues/488 is closed

### CODE REVIEW

**Review by dave-doty — CHANGES_REQUESTED** [review]
I'm a bit confused. This looks like very little changed. Just one file, and essentially only comments in that file changed.

**Comment by UnHumbleBen** [comment]
I think there isn't much to change in the python package? I thought most of
the change would be in the scadnano web app.

**Review by dave-doty — APPROVED** [review]
Oops, didn't notice which repo it is.

**Comment by UnHumbleBen** [comment]
@dave-doty I changed the scripts associated with the `output_designs` directory. Are there any scripts associated with the `proposal` directory? Or should I change those manually (i.e. load them into my local hosted scadnano so that they automatically get converted into version 0.13.0, and then Save that new file).

Another thing that comes to mind is does the cadnano import need to be rewritten? I imagine it doesn't because cadnano doesn't have gridless option, but just want to make sure.

Once I add the changes to `proposal` examples, and copy the examples directory into the scadnano web app repo, should be ready to merge :smile:

**Comment by dave-doty** [comment]
> Are there any scripts associated with the proposal directory?

No, proposal isn't used in the dropdown menu of examples.

> Another thing that comes to mind is does the cadnano import need to be rewritten?

Try importing a cadnano design and see if it works.

**Comment by UnHumbleBen** [comment]
I am actually confused about the purpose of the `examples/` directory in `web/`. Besides the files that are listed in the dropdown menu, what is the purpose of the other files that are not on the dropdown menu? They cannot be viewed normally from using the app.

**Comment by dave-doty** [comment]
> I am actually confused about the purpose of the `examples/` directory in `web/` of the scadnano web app. Besides the files that are listed in the dropdown menu, what is the purpose of the other files that are not on the dropdown menu? They cannot be viewed normally from using the app.

Pure laziness. This way I can run a script that copies all examples from the Python repo to here, without thinking about which ones are used in the dropdown menu.

**Pull request merged**
