### PR TITLE
Bug fix helix number was badly set in cadnano export

### PR DESCRIPTION
**Pull request by tcosmo**
https://github.com/UC-Davis-molecular-computing/scadnano-python-package/issues/185

### CODE REVIEW

**Review by dave-doty — CHANGES_REQUESTED** [review]
Looks like the unit tests are failing.

**Comment by tcosmo** [comment]
@dave-doty it is fixed, it came from the messy situation that tests_inputs/cadnano_v2_export/ are gitignored because most of them are automatically generated but in the paranemic case, the test is not generated but to be read from a .sc file so it was failing because the file was not found.

**Review by dave-doty — APPROVED** [review]

**Comment by tcosmo** [comment]
@dave-doty I mistakenly did the pull request to main, should I move it to dev?

Also note that the tests for the import/export features are quite weak as they do not check, for example in the case of exporting to cadnano, that cadnano can actually read the file. 

It results for instance in test 'TestExportCadnanoV2.test_export_design_with_helix_group' creating a file that cadnano cannot process.

**Comment by dave-doty** [comment]
> @dave-doty I mistakenly did the pull request to main, should I move it to dev?

Good catch, yes please merge to dev instead of main.

**Pull request merged**
