### PR TITLE
v0.16.0

### PR DESCRIPTION
**Pull request by UnHumbleBen**

### CODE REVIEW

**Comment by UnHumbleBen** [comment]
doc test failed even though docs compiled just fine locally.

I suspect it is because the [action](https://github.com/ammaraskar/sphinx-action) we are using depends on an earlier version of Sphinx (2.4.4)

When I run
```
pip install -Iv sphinx==2.4.4
```
to installed that version, and run `make html` I get build error:
```
Running Sphinx v2.4.4

Extension error:
Event 'html-collect-pages' already present
Makefile:20: recipe for target 'html' failed
make: *** [html] Error 2
```

The action does not seem reliable as it has been more than a year since last update on the repo and it does not have a versioning to ensure stability going into the future. Probably time to revisit the doc check github action so that it doesn't rely on their action

**Review by dave-doty — CHANGES_REQUESTED** [review]
Let's not merge all of these changes yet. In particular, there are breaking changes with regard to removing `pitch` and `yaw` from `Helix`, and I want to make sure we are handling that properly both here and in the Dart code before merging into main.

Is there a way to include only the commit(s) involving changing the name of the main branch?

Also, it would be good to find a new way to have a GitHub Action that tests if the docs compile properly.

**Comment by UnHumbleBen** [comment]
> Is there a way to include only the commit(s) involving changing the name of the main branch?

A hotfix branch could be made that merges directly to main containing just the change to the workflow. Alternatively, we can just wait since the only workflow that was affected is `release.yml` and this workflow doesn't run until we merge to `main` anyways.

> Also, it would be good to find a new way to have a GitHub Action that tests if the docs compile properly.
Agreed, I will make an issue on this

**Comment by UnHumbleBen** [comment]
[scadnano PR v0.16.0](https://github.com/UC-Davis-molecular-computing/scadnano/pull/602) ready!

**Comment by dave-doty** [comment]
Can we try to fix the "Docs Check" action as part of this PR as well? I'd like to get that back to a state where it doesn't have a false alarm. (I haven't compiled the docs locally recently, so I don't even know whether the current alarm is false, but the check is not passing.)

**Comment by UnHumbleBen** [comment]
> Can we try to fix the "Docs Check" action as part of this PR as well? I'd like to get that back to a state where it doesn't have a false alarm. (I haven't compiled the docs locally recently, so I don't even know whether the current alarm is false, but the check is not passing.)

Ok, I'll look into it

**Comment by UnHumbleBen** [comment]
@dave-doty While working on docs check workflow, I found that you can [subscribe to notifications](https://readthedocs.org/dashboard/scadnano-python-package/notifications/) on the ReadTheDocs project site so that you get notified via email if a build fails.

**Review by dave-doty — APPROVED** [review]
Can you please add to the release notes that there is a breaking change?

It would also be good to document this change: fixes #168: ensure grid fields are of type Grid, not str or None, since it might break existing code that was manually passing in strings for the grid parameter.

**Pull request merged**
